Add property
greg-Da/realestate-react pull request #3
Opened 2023-11-28 18:48 UTC by greg-Da

2023-11-28 22:13 UTC, Creiwry requested changes

2023-11-28 22:13 UTC, Creiwry commented on src/pages/Register.jsx
> +              value={firstName}
First name and last name are not submitable on devise register. I might just remove them all together from the model to be honest, I think we only need a page to change the email address and password

2023-11-28 22:13 UTC, Creiwry commented on src/pages/Property/New.jsx
> +              onChange={() => setTerrasse(!terrasse)}
It's "Terrace" in English

2023-11-29 10:51 UTC, greg-Da commented on src/pages/Property/New.jsx
> +              onChange={() => setTerrasse(!terrasse)}
ahah sorry I ll change it

2023-11-29 15:33 UTC, Creiwry approved these changes
awesome

2023-11-29 15:36 UTC, merged